In [26]:
# The following code is only for Google Colab.
# If you are running this notebook locally, you should not run this cell.

# %pip install google-colab

# from google.colab import drive
# drive.mount('/content/drive/')

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import re
import zipfile
from textblob import TextBlob
from pathlib import Path
from nltk.tokenize import RegexpTokenizer
from nltk.stem import PorterStemmer, WordNetLemmatizer
from spellchecker import SpellChecker
from nltk.corpus import wordnet
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to /Users/vongoc/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/vongoc/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /Users/vongoc/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/vongoc/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [68]:
current_directory = Path(__file__).parent if '__file__' in locals() else Path.cwd()
print(f"Current directory: {current_directory}")
with zipfile.ZipFile(f"{current_directory}/data.zip", 'r') as zip_ref:
    zip_ref.extractall(current_directory)

Current directory: /Users/vongoc/Documents/GitHub/ASM3-APDS

In [69]:
df = pd.read_csv('data/assignment3.csv')
df

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
1,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
2,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
3,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses
4,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits
...,...,...,...,...,...,...,...,...,...,...
19657,1104,34,Great dress for many occasions,I was very happy to snag this dress at such a ...,5,1,0,General Petite,Dresses,Dresses
19658,862,48,Wish it was made of cotton,"It reminds me of maternity clothes. soft, stre...",3,1,0,General Petite,Tops,Knits
19659,1104,31,"Cute, but see through","This fit well, but the top was very see throug...",3,0,1,General Petite,Dresses,Dresses
19660,1084,28,"Very cute dress, perfect for summer parties an...",I bought this dress for a wedding i have this ...,3,1,2,General,Dresses,Dresses
19661,1104,52,Please make more like this one!,This dress in a lovely platinum is feminine an...,5,1,22,General Petite,Dresses,Dresses

In [70]:
# 2/3/4. Tokenizing clothing review

# define tokenizer
tokenizer = RegexpTokenizer(r"[a-zA-Z]+(?:[-'][a-zA-Z]+)?")

# Tokenize the review text + lowercasing and removing words with length < 2
df["tokens"] = (
    df["Review Text"]
      .fillna("") # replace NaN with empty string
      .astype(str)
      .apply(lambda text: [token.lower() for token in tokenizer.tokenize(text) if len(token) > 1])
)

# quick spot-checks (delete when done)
print(df["tokens"].head(3).tolist())
assert isinstance(df["tokens"].iloc[0], list)

[['had', 'such', 'high', 'hopes', 'for', 'this', 'dress', 'and', 'really', 'wanted', 'it', 'to', 'work', 'for', 'me', 'initially', 'ordered', 'the', 'petite', 'small', 'my', 'usual', 'size', 'but', 'found', 'this', 'to', 'be', 'outrageously', 'small', 'so', 'small', 'in', 'fact', 'that', 'could', 'not', 'zip', 'it', 'up', 'reordered', 'it', 'in', 'petite', 'medium', 'which', 'was', 'just', 'ok', 'overall', 'the', 'top', 'half', 'was', 'comfortable', 'and', 'fit', 'nicely', 'but', 'the', 'bottom', 'half', 'had', 'very', 'tight', 'under', 'layer', 'and', 'several', 'somewhat', 'cheap', 'net', 'over', 'layers', 'imo', 'major', 'design', 'flaw', 'was', 'the', 'net', 'over', 'layer', 'sewn', 'directly', 'into', 'the', 'zipper', 'it'], ['love', 'love', 'love', 'this', 'jumpsuit', "it's", 'fun', 'flirty', 'and', 'fabulous', 'every', 'time', 'wear', 'it', 'get', 'nothing', 'but', 'great', 'compliments'], ['this', 'shirt', 'is', 'very', 'flattering', 'to', 'all', 'due', 'to', 'the', 'adjustable', 'front', 'tie', 'it', 'is', 'the', 'perfect', 'length', 'to', 'wear', 'with', 'leggings', 'and', 'it', 'is', 'sleeveless', 'so', 'it', 'pairs', 'well', 'with', 'any', 'cardigan', 'love', 'this', 'shirt']]

In [71]:
def correct_text(text):
    return str(TextBlob(text).correct())

def correct_tokens(token_list):
    corrected_tokens = []
    for token in token_list:
        corrected_token = correct_text(token)
        corrected_tokens.append(corrected_token)
    return corrected_tokens

df["tokens"] = df["tokens"].apply(correct_tokens)

In [72]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import wordnet
from spellchecker import SpellChecker
import nltk

lemmatizer = WordNetLemmatizer()
spell = SpellChecker()

# -------------------------------
# Step 0: Clean tokens
# -------------------------------
def clean_tokens(tokens):
    if not isinstance(tokens, list):
        return []
    return [str(t).lower() for t in tokens if t is not None]

# -------------------------------
# Step 1: Spell checking
# -------------------------------
def correct_tokens(tokens):
    corrected = []
    for word in tokens:
        if word in spell.unknown([word]):
            suggestion = spell.correction(word)
            corrected.append(suggestion if suggestion is not None else word)
        else:
            corrected.append(word)
    return corrected


# -------------------------------
# Step 2: POS mapping for Lemmatization
# -------------------------------
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# -------------------------------
# Step 3: Lemmatization 
# -------------------------------
def lemmatize_tokens(tokens):
    pos_tags = nltk.pos_tag([str(t) for t in tokens if t])
    lemmatized = []
    for word, pos in pos_tags:
        wn_pos = get_wordnet_pos(pos)
        # Heuristic for verbsx
        lemma = lemmatizer.lemmatize(word, wn_pos)
        lemmatized.append(lemma)
    return lemmatized

# -------------------------------
# Apply pipeline
# -------------------------------
df["tokens"] = df["tokens"].apply(clean_tokens)
df["tokens"] = df["tokens"].apply(correct_tokens)
df["tokens"] = df["tokens"].apply(lemmatize_tokens)

In [75]:
# 5. Remove stopwords using the provided stop words list (i.e., stopwords_en.txt). It is located inside the same downloaded folder. 
# Find file stopwords in data
stop_candidates = [Path("stopwords_en.txt"), Path("data/stopwords_en.txt")]
stop_path = next((p for p in stop_candidates if p.exists()), None)
assert stop_path is not None, "stopwords_en.txt not found. Please put it in project root or inside data/."

# Load stopwords
with open(stop_path, "r", encoding="utf-8") as f:
    STOPWORDS = {line.strip() for line in f if line.strip()}

print(f"[Q5] Loaded {len(STOPWORDS)} stopwords from {stop_path}")

# Remove stopwords (Compare lowercase)
def remove_stopwords(tokens, stopset):
    return [t for t in tokens if t.lower() not in stopset]

df["tokens"] = df["tokens"].apply(lambda xs: remove_stopwords(xs, STOPWORDS))

# Print to check
print(df[["tokens"]].head(2))
print("df['tokens'] ready for Step 6 & 7.")

[Q5] Loaded 570 stopwords from data/stopwords_en.txt
                                              tokens
0  [high, hope, dress, work, initially, order, pe...
1  [love, love, love, jumpsuit, fun, flirt, fabul...
df['tokens'] ready for Step 6 & 7.

In [76]:
df[["tokens"]].head(50)

                                               tokens
0   [high, hope, dress, work, initially, order, pe...
1   [love, love, love, jumpsuit, fun, flirt, fabul...
2   [shirt, flattering, due, adjustable, front, ti...
3   [love, trace, geese, dress, petite, foot, tall...
4   [add, basket, minute, person, store, pick, dar...
5   [order, carbon, store, pick, ton, stuff, top, ...
6   [love, dress, run, snug, bust, order, size, fl...
7   [le, order, petite, make, length, long, typica...
8   [dress, run, small, nipper, area, run, order, ...
9   [find, radiant, review, write, navvy, shipper,...
10  [buy, black, larkspur, mid, dress, bother, lin...
11  [nice, choice, holiday, gathering, length, gra...
12  [package, fit, badly, put, hourglass, figure, ...
13  [material, color, nice, leg, opening, large, l...
14  [chance, louse, glad, crazy, louse, photograph...
15  [flatter, super, copy, coat, work, cold, dry, ...
16  [love, feel, dress, top, year's, eve, small, c...
17  [product, petite, petite, regular, long, tailo...
18  [upset, price, dress, embroider, print, fabric...
19  [plover, side, nipper, purchase, side, nipper,...
20  [cut, dress, fit, high, waisted, good, length,...
21  [love, shirt, shirt, dress, see-through, wear,...
22  [love, material, long, dress, purchase, large,...
23  [wait, sweeter, coat, ship, week, excited, arr...
24  [color, expect, dark, blue, vagrant, find, fab...
25  [goodhyouman, shirt, compliment, forehead, kis...
26  [sweeter, classic, balance, quickly, hand-knit...
27  [give, part, online, person, outer, stripe, br...
28               [part, person, downside, dry, clean]
29  [order, month, ago, finally, back, order, huge...
30  [neat, dress, color, great, fabric, super, sof...
31                    [give, store, whim, love, love]
32  [order, small, size, medium, mon, size, gorgeo...
33  [porch, cut, love, plaid, check, design, color...
34  [thermal, naturally, expect, super, sheer, she...
35  [today, local, retailer, comfortable, flatteri...
36  [buy, item, online, fit, model, loose, mine, b...
37  [sweeter, perfect, fall, room, warm, super, co...
38  [cut, top, embroidery, collar, big, top, beaut...
39  [cut, top, transition, easily, summer, fall, f...
40  [absolutely, love, big, favorite, retailer, pu...
41  [soft, comfortable, shirt, unusual, symmetrica...
42  [nice, top, armhole, bit, oversized, woman, pi...
43  [adorable, top, find, extremely, comfortable, ...
44  [tank, fit, love, ruffle, back, play, front, g...
45  [brunette, provide, support, bind, tight, nigh...
46  [dress, simply, beautiful, stun, figure, flatt...
47  [tag, sew, small, long, huge, itchy, cut, thre...
48  [recently, sale, forever, list, happy, comfort...
49  [comfortable, shirt, light, weight, top, lovel...

In [79]:
# 6. Remove the word that appears only once in the document collection, based on term frequency.
term_freq = pd.Series(np.concatenate(df["tokens"].values)).value_counts()
 
df["tokens"] = df["tokens"].apply(lambda tokens: [token for token in tokens if term_freq[token] > 1])

# Double check
term_freq = pd.Series(np.concatenate(df["tokens"].values)).value_counts()
term_freq

dress         10944
fit            9723
love           8944
size           8905
wear           8442
              ...
bonnet            2
knit-like         2
pillowcase        2
rewashed          2
crossway          2
Name: count, Length: 5274, dtype: int64

In [83]:

# 7. Remove the top 20 most frequent words based on document frequency. 
top_20_words = term_freq.nlargest(20).index
df["tokens"] = df["tokens"].apply(lambda tokens: [token for token in tokens if token not in top_20_words])

# Double check
term_freq = pd.Series(np.concatenate(df["tokens"].values)).value_counts()
term_freq

comfortable    2709
run            2668
short          2606
work           2589
long           2538
               ...
elevated          2
obscure           2
mock-neck         2
disastrous        2
crossway          2
Name: count, Length: 5254, dtype: int64

In [103]:
def clean_vocab_token(token):
    token = token.lower().strip()
    if re.fullmatch(r"[a-z0-9]+", token) and len(token) > 2:
        return token
    return None

cleaned_tokens = df["tokens"].apply(lambda tokens: [clean_vocab_token(t) for t in tokens if t is not None])
df["tokens"] = cleaned_tokens.apply(lambda tokens: [t for t in tokens if t is not None])

In [104]:
df[["tokens"]].head(50)

                                               tokens
0   [high, hope, work, initially, petite, usual, f...
1   [jumpsuit, fun, flirt, fabulous, time, complim...
2   [flattering, due, adjustable, front, tie, leng...
3   [trace, geese, petite, foot, tall, brand, pret...
4   [add, basket, minute, person, store, pick, dar...
5   [carbon, store, pick, ton, stuff, pair, skirt,...
6   [run, snug, bust, flattering, feminine, usual,...
7   [petite, length, long, typically, regular, ret...
8   [run, nipper, area, run, typically, tight, mat...
9   [find, radiant, review, write, navvy, shipper,...
10  [black, larkspur, mid, bother, line, skirt, po...
11  [choice, holiday, gathering, length, grade, kn...
12  [package, badly, put, hourglass, figure, strai...
13  [material, leg, opening, length, hit, ankle, l...
14  [chance, louse, glad, crazy, louse, photograph...
15  [flatter, super, copy, coat, work, cold, dry, ...
16  [feel, eve, chester, form, flatter, steam, len...
17  [product, petite, petite, regular, long, tailo...
18  [upset, price, embroider, print, cry, open, bo...
19  [plover, side, nipper, purchase, side, nipper,...
20  [high, waisted, good, length, height, feel, ch...
21  [slip, legging, slip, tie, rock, white, edge, ...
22  [material, long, purchase, medium, material, f...
23  [wait, sweeter, coat, ship, week, excited, arr...
24  [expect, dark, blue, vagrant, find, thick, goo...
25                       [compliment, kiss, hesitate]
26  [sweeter, classic, balance, quickly, beautiful...
27  [give, part, online, person, outer, stripe, br...
28               [part, person, downside, dry, clean]
29  [month, ago, finally, huge, disappointment, is...
30  [neat, super, tall, long, length, added, bonus...
31                                [give, store, whim]
32  [medium, mon, gorgeous, beautifully, drape, we...
33  [porch, plaid, check, design, street, cream, p...
34  [thermal, naturally, expect, super, sheer, she...
35  [today, local, retailer, comfortable, flatteri...
36  [item, online, model, loose, mine, bit, tight,...
37            [sweeter, fall, room, warm, super, pip]
38  [embroidery, collar, big, beautiful, unique, r...
39  [transition, easily, summer, fall, print, comf...
40  [absolutely, big, favorite, retailer, purchase...
41  [comfortable, unusual, symmetrical, seat, fron...
42  [armhole, bit, oversized, woman, pick, print, ...
43  [adorable, find, extremely, comfortable, print...
44          [tank, ruffle, play, front, good, return]
45  [brunette, provide, support, bind, tight, nigh...
46  [simply, beautiful, stun, figure, flattering, ...
47  [tag, sew, long, huge, itchy, thread, leave, p...
48  [recently, sale, forever, list, happy, comfort...
49  [comfortable, light, weight, lovely, flora, sp...

In [106]:
from collections import Counter

# Flatten all tokens
all_tokens = [t for tokens in df["tokens"] for t in tokens]


token_counts = Counter(clean_tokens)
token_counts

# Sort vocab
unique_vocab = sorted(all_tokens)
vocab_dict = {word: idx for idx, word in enumerate(unique_vocab)}

# Extract vocab
with open("vocabulary.txt", "w", encoding="utf-8") as f:
    for word, idx in vocab_dict.items():
        f.write(f"{word}:{idx}\n")

df.to_csv("processed.csv", index=False)